# Generated by Django 4.0.4 on 2022-04-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionName', models.CharField(max_length=200)),
                ('questionStatement', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=10)),
                ('tags', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='testCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase', models.TextField()),
                ('output', models.TextField()),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.questions')),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('verdict', models.CharField(max_length=25)),
                ('submitted_at', models.DateTimeField(verbose_name='Submission Time')),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.questions')),
            ],
        ),
    ]
