# Generated by Django 4.0.4 on 2022-04-30 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineJudge', '0002_alter_questions_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Submission Time'),
        ),
        migrations.CreateModel(
            name='verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('AC', 'success'), ('TLE', 'timeLimitExceeded'), ('WA', 'wrongAnswer'), ('COMPILATION_ERROR', 'compilationError')], default='WA', max_length=30)),
                ('submittedAt', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
                ('problemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineJudge.questions')),
            ],
        ),
    ]
